name: Build Release Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          targets: aarch64-apple-darwin
      
      - name: Build for macOS (x86_64)
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Building DualMind v$VERSION for macOS (x86_64)"
          cargo build --release
          
          mkdir -p releases
          cp target/release/dualmind releases/dualmind-$VERSION-x86_64-macos
          cp .env.example releases/
          cp README.md releases/
      
      - name: Build for macOS (ARM64)
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Building DualMind v$VERSION for macOS (ARM64)"
          cargo build --release --target aarch64-apple-darwin
          
          cp target/aarch64-apple-darwin/release/dualmind releases/dualmind-$VERSION-arm64-macos
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      
      - name: Build Flutter macOS App
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          cd chat_app
          flutter pub get
          flutter build macos --release
          
          # Package the macOS app
          cd build/macos/Build/Products/Release
          zip -r ../../../../../../releases/dualmind-flutter-$VERSION-macos.zip DualMind.app
      
      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: releases/*
  
  build-linux-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Build for Linux (x86_64)
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Building DualMind v$VERSION for Linux (x86_64)"
          cargo build --release
          
          mkdir -p releases
          cp target/release/dualmind releases/dualmind-$VERSION-x86_64-linux
          cp .env.example releases/
          cp README.md releases/
      
      - name: Install Linux dependencies for Flutter
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      
      - name: Build Flutter Linux App
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          cd chat_app
          flutter pub get
          flutter config --enable-linux-desktop
          flutter build linux --release
          
          # Package the Linux app
          cd build/linux/x64/release/bundle
          tar -czvf ../../../../../releases/dualmind-flutter-$VERSION-linux-x64.tar.gz *
      
      - name: Upload Linux x86_64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86-build
          path: releases/*
  
  build-linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          targets: aarch64-unknown-linux-gnu
      
      - name: Install cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      
      - name: Build for Linux (ARM64)
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Building DualMind v$VERSION for Linux (ARM64)"
          
          # Use cross-compilation for ARM64
          cargo install cross --git https://github.com/cross-rs/cross
          cross build --release --target aarch64-unknown-linux-gnu
          
          mkdir -p releases
          cp target/aarch64-unknown-linux-gnu/release/dualmind releases/dualmind-$VERSION-arm64-linux
          cp .env.example releases/
          cp README.md releases/
      
      - name: Upload Linux ARM64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm-build
          path: releases/*
  
  create-release:
    needs: [build-macos, build-linux-x86, build-linux-arm]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      
      - name: List downloaded files
        run: find . -type f | sort
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            macos-build/*
            linux-x86-build/*
            linux-arm-build/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 